version: "3"
services:
  app:
    image: node:12-alpine
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app:cached
    depends_on:
      - redis
      - mongo
    extra_hosts:
      - "api.github.com:140.82.113.6"

  mongo:
    image: mongo:3.4.7
    # 等于 .env 文件里的变量
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:
      MONGO_INITDB_USERNAME:
      MONGO_INITDB_PASSWORD:
    volumes:
      - ./data/db:/data/db:cached
      - ./data/config/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:cached

  redis:
    image: redis:5.0.7
    volumes:
      - ./data/redis:/data:cached
      - ./data/config/redis.conf:/etc/redis.conf:cached
    command: ["redis-server", "/etc/redis.conf"]