version: "3"
services:
  app:
    image: node:12-alpine
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo:3.4.7
    # 等于 .env 文件里的变量
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:
      MONGO_INITDB_USERNAME:
      MONGO_INITDB_PASSWORD:
    volumes:
      - ./data/db:/data/db
      - ./data/config/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  redis:
    image: redis:5.0.7
    volumes:
      - ./data/redis:/data
      - ./data/config/redis.conf:/etc/redis.conf
    command: ["redis-server", "/etc/redis.conf"]